activate/activate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('', include('usermanagement.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGES_URL, document_root=settings.IMAGES_ROOT)

activate/events/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.activity_list, name='activity_list'),
    path('create/', views.create_activity, name='create_activity'),
    path('<int:id>/', views.activity_detail_view, name='activity_detail_view'),
    url(r'^register/(\d+)/$', views.register, name='register'),
    url(r'^unregister/(\d+)/$', views.unregister, name='unregister'),
    url(r'^cancel/(\d+)/$', views.cancel_activity, name='cancel_activity'),
    path('me/', views.organized_activities_view, name='organized_activities')
]

activate/usermanagement/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from activate.settings import LOGOUT_REDIRECT_URL as LOGOUT
from . import views

app_name = 'usermanagement'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='usermanagement/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page=LOGOUT), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
]

activate/activate/templates/base.html
{% load static %}

<html>
    <head>
        <title>Activate</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <script src="https://kit.fontawesome.com/9b392f9531.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <!-- Header -->
        <nav class="navbar navbar-light navbar-expand-lg bg-white d-flex shadow-sm">
            <a class="navbar-brand" href="/">Activate</a>
            {% if not user.is_anonymous %}<a href="{% url 'events:create_activity' %}" class="mr-3">Lag aktivitet</a>{% endif %}
            {% if not user.is_anonymous %}<a href="{% url 'events:organized_activities' %}" class="mr-3">Mine aktiviteter</a>{% endif %}
            <div class="ml-auto">
                {% if not user.is_authenticated %}
                    <a class="btn btn-link" href="{% url 'usermanagement:login' %}">Login</a>
                    <a class="btn btn-primary" href="{% url 'usermanagement:signup' %}">Signup</a>
                {% else %}
                    <a class="btn btn-link" href="{% url 'usermanagement:logout' %}">Logg ut</a>
                    <a class="btn btn-primary" href="{% url 'usermanagement:profile' %}">Min profil</a>
                {% endif %}
            </div>
        </nav>
        <!-- Content -->
        <div class="content container">
            <div class="row justify-content-center">
                <div class="col-md-9">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>

        <!-- Bootstrap & jQuery -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>