activate/activate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('', include('usermanagement.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.IMAGES_URL, document_root=settings.IMAGES_ROOT)

activate/events/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.activity_list, name='activity_list'),
    path('create/', views.create_activity, name='create_activity'),
    path('<int:id>/', views.activity_detail_view, name='activity_detail_view'),
    url(r'^register/(\d+)/$', views.register, name='register'),
    url(r'^unregister/(\d+)/$', views.unregister, name='unregister'),
    url(r'^cancel/(\d+)/$', views.cancel_activity, name='cancel_activity'),
    path('me/', views.organized_activities_view, name='organized_activities')
]

activate/usermanagement/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from activate.settings import LOGOUT_REDIRECT_URL as LOGOUT
from . import views

app_name = 'usermanagement'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='usermanagement/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page=LOGOUT), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
]

activate/events/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models import F, Count, Case, When, Value, BooleanField
from django.utils import timezone


class ActivityManager(models.Manager):
    """QuerySet manager for Activity class to add non-database fields.

    A @property in the model cannot be used because QuerySets (eg. return
    value from .all()) are directly tied to the database Fields -
    this does not include @property attributes."""

    def get_queryset(self):
        """Overrides the models.Manager method"""
        num_participants = Count('registered_users')
        qs = super(ActivityManager, self).get_queryset().annotate(num_participants=Count('registered_users'))
        qs = qs.annotate(is_full=Case(
            When(max_participants__isnull=True, then=Value(False)),
            When(num_participants__gte=F('max_participants'), then=Value(True)),
            default=Value(False),
            output_field=BooleanField()
        ))
        return qs


class Activity(models.Model):
    """Model for activities. Contains all necessary info for a single activity event."""
    title = models.CharField(max_length=200, verbose_name="tittel")
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    # CASCADE: If the user gets deleted, the corresponding activities will also be deleted
    responsible = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(app_label)s_%(class)s_responsible')

    date = models.DateField(verbose_name="fra dato", default=datetime.date.today, blank=True)
    time_from = models.TimeField(verbose_name="time from", default=timezone.now, blank=True)
    time_to = models.TimeField(verbose_name="time to", default=2, blank=True)

    gear = models.CharField(max_length=200, verbose_name="utstyr", default='')
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0, null=True, verbose_name='pris')

    max_participants = models.IntegerField(default=0, null=True, verbose_name='maks_deltagere')
    registered_users = models.ManyToManyField(User, blank=True, verbose_name='påmeldte brukere',
                                              related_name='%(app_label)s_%(class)s_registered')
    meeting_place = models.CharField(max_length=200, verbose_name="oppmøtested")

    show_email_address = models.BooleanField(verbose_name="vis_e-post", default=False)
    krever_NTNUI_medlemskap = models.BooleanField(default=False)
    cancelled = models.BooleanField(default=False)  # Is the activity cancelled?

    # Overridden objects manager
    objects = ActivityManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Activities"
        ordering = ['date', 'time_from', 'krever_NTNUI_medlemskap']

activate/events/forms.py
import datetime
from crispy_forms.bootstrap import FieldWithButtons, StrictButton
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Div
from django import forms

from .models import Activity


class CreateActivityForm(forms.ModelForm):
    title = forms.CharField(label='Tittel', max_length=200)
    text = forms.CharField(label='Beskrivelse', widget=forms.Textarea())
    date = forms.DateField(label='Dato',
                           widget=forms.SelectDateWidget
                           (years=[x for x in range(datetime.datetime.now().year, datetime.datetime.now().year + 2)]),
                           required=False)
    time_from = forms.TimeField(label='Start tidspunkt', help_text='F.eks.: 16:30')
    time_to = forms.TimeField(label='Slutt tidspunkt', help_text='F.eks.: 18:00')

    max_participants = forms.IntegerField(label='Antall deltagere', required=False, help_text='Valgfri.')
    gear = forms.CharField(label='Utstyr', max_length=200, required=False, help_text='Valgfri.')
    price = forms.DecimalField(label='Pris', required=False, help_text='Valgfri.')
    meeting_place = forms.CharField(label='Oppmøtested', max_length=200, help_text='Må være tydelig.')

    show_email_address = forms.BooleanField(label='Vis e-post',
                                            required=False,
                                            help_text='Vis e-postadresse slik at deltakere kan ta kontakt.')
    # This name is in norwegian because it shows on the form. '_' are replaced with ' '.
    krever_NTNUI_medlemskap = forms.CheckboxInput()

    class Meta:
        model = Activity
        fields = ('title', 'text', 'date', 'time_from', 'time_to', 'max_participants', 'gear', 'price', 'meeting_place',
                  'show_email_address', 'krever_NTNUI_medlemskap')


class FilterForm(forms.Form):
    search = forms.CharField(max_length=255, required=False)
    available = forms.BooleanField(label="Kun ledige", required=False)
    hide_ntnui = forms.BooleanField(label="Skjul NTNUI-aktiviteter", required=False)
    free = forms.BooleanField(label="Kun gratis", required=False)

    helper = FormHelper()
    helper.disable_csrf = True
    search.label = False
    helper.layout = Layout(
        FieldWithButtons(
            Field('search', placeholder="Søk..."),
            StrictButton('<i class="fas fa-search"></i>', value='submit', type='submit', css_class='btn-primary'),
            css_class="form-row ml-0"
        ),
        Div(
            Field('available', type="checkbox", css_class="custom-control-input"),
            css_class="custom-control custom-switch pl-3"
        ),
        Div(
            Field('hide_ntnui', type="checkbox", css_class="custom-control-input"),
            css_class="custom-control custom-switch pl-3"
        ),
        Div(
            Field('free', type="checkbox", css_class="custom-control-input"),
            css_class="custom-control custom-switch pl-3"
        ),
        StrictButton('Søk', value='submit', type='submit', css_class='btn-primary')
    )

activate/events/views.py
import datetime

from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from activate import settings
from .forms import CreateActivityForm, FilterForm
from .models import Activity


def activity_list(request):
    """Returns activities based on request filters"""
    # Start by returning all activities
    activities = Activity.objects.all()
    filter_form = FilterForm(request.GET or None)

    search_query = ''
    filter_query = Q()

    # Filter only upcoming activities
    filter_query &= Q(date__gte=datetime.date.today())

    if filter_form.is_bound and filter_form.is_valid():
        filters = filter_form.cleaned_data
        search_query = filters.get("search")
        if search_query:
            filter_query &= (
                Q(title__icontains=search_query) |
                Q(text__icontains=search_query)
            )
        if filters.get("available"):
            filter_query &= (
                Q(is_full=False)
            )
        if filters.get("hide_ntnui"):
            filter_query &= (
                Q(krever_NTNUI_medlemskap=False)
            )
        if filters.get("free"):
            filter_query &= (
                Q(price=0)
            )
    activities = activities.filter(filter_query)

    context = {
        'activities': activities,
        'filter_form': filter_form,
        'query_string': search_query,
    }
    return render(request, 'events/activity_list.html', context)


def create_activity(request):
    """Create activity"""
    # User is rejected if they are not logged in
    if request.user is None or request.user.is_anonymous:
        return activity_list(request)

    if request.method == 'POST':
        form = CreateActivityForm(request.POST)
        if form.is_valid():
            activity = form.save(commit=False)  # Create activity object, but do not commit it to the database just yet
            activity.responsible = request.user  # Add the currently logged in user as 'responsible' for this activity
            activity.save()  # Save the activity to the database

            return redirect('/' + str(activity.id))  # Redirects to the home page
    else:
        form = CreateActivityForm()

    return render(request, 'events/activity_create.html', {'form': form})


@login_required
def cancel_activity(request, id):
    # Make sure the activity is not already cancelled
    activity = Activity.objects.get(id=id)
    if not activity.cancelled and request.user == activity.responsible and activity.date > datetime.date.today():
        activity.cancelled = True
        activity.save()

        for user in activity.registered_users.all():
            email_activity_cancellation(activity, user)

    return redirect('/' + str(id))


def email_activity_cancellation(activity, user):
    send_mail(
        'Et arrangement du er påmeldt er blitt kansellert!',
        '"' + activity.title + '" er kansellert.\n\n'
        'For mer informasjon se arrangementsiden:\n'
        'http://127.0.0.1:8000/' + str(activity.id),
        settings.EMAIL_HOST_USER,
        [user.email],
        fail_silently=False,
    )


def activity_detail_view(request, id):
    """Returns detailed activity view"""
    activity = Activity.objects.get(id=id)  # Gets right activity
    date = datetime.date.today()
    return render(request, 'events/activity_detail_view.html', {'activity': activity, 'date': date})


def register(request, activity_id):
    """Register for an activity"""
    activity = get_object_or_404(Activity, id=activity_id)

    if activity.max_participants is None or activity.registered_users.count() <= activity.max_participants:
        activity.registered_users.add(request.user.id)
        messages.info(request, u'Du er nå meldt på %s.' % activity.title)
    else:
        messages.info(request, u'Arrangementet er fullt %s.' % activity.title)

    return redirect('/')


def unregister(request, activity_id):
    """Deregister from an activity"""
    activity = get_object_or_404(Activity, id=activity_id)

    activity.registered_users.remove(request.user.id)
    messages.info(request, u'Du er nå meldt av %s.' % activity.title)

    return redirect('/')


@login_required
def organized_activities_view(request):
    """Returns list of all activities you are arranging, participating in, have arranged or have participated in"""
    arranged_activities = Activity.objects.filter(responsible=request.user).filter(date__gte=datetime.date.today())
    upcoming_activities = Activity.objects.filter(registered_users=request.user).filter(date__gte=datetime.date.today())
    earlier_arranged_activities = Activity.objects.filter(responsible=request.user).filter(date__lte=datetime.date.today())
    earlier_activities = Activity.objects.filter(registered_users=request.user).filter(date__lte=datetime.date.today())

    return render(request, 'events/activity_upcoming.html',
                  {
                      'arranged_activities': arranged_activities,
                      'upcoming_activities': upcoming_activities,
                      'earlier_activities': earlier_activities,
                      'earlier_arranged_activities': earlier_arranged_activities
                  })

activate/events/templates/events/activity_button_reg_detail.html
{% if activity.cancelled %}
    <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true">Arrangementet er kansellert</a>
{% else %}
    {% if not user.is_anonymous %}
        {% if user.id == activity.responsible.id %}
            <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true">Du er arrangør</a>
        {% elif not user.profile.NTNUI_medlem and activity.krever_NTNUI_medlemskap %}
            <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true"><i class="fas fa-lock"></i> Krever NTNUI-medlemskap </a>
        {% elif user in activity.registered_users.all %}
            <a href="{% url 'events:unregister' activity.id %}" class="btn btn-danger mt-1 stretched-link" aria-disabled="true">Meld av</a>
        {% elif activity.max_participants <= activity.registered_users.count %}
            <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true">Arrangementet er fullt</a>
        {% else %}
            <a href="{% url 'events:register' activity.id %}" class="btn btn-primary mt-1 stretched-link">Meld deg på</a>
        {% endif %}
    {% else %}
        <a href="{% url 'usermanagement:login' %}" class="btn btn-outline-primary stretched-link" role="button">Logg inn for å melde deg på</a>
    {% endif %}
{% endif %}

activate/events/templates/events/activity_button_register.html
{% if activity.cancelled %}
    <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true">Arrangementet er kansellert</a>
{% else %}
    {% if not user.is_anonymous %}
        {% if user.id == activity.responsible.id %}
            <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true">Du er arrangør</a>
        {% elif not user.profile.NTNUI_medlem and activity.krever_NTNUI_medlemskap %}
            <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true"><i class="fas fa-lock"></i> Krever NTNUI-medlemskap </a>
        {% elif user in activity.registered_users.all %}
            <a href="{% url 'events:unregister' activity.id %}" class="mt-1 stretched-link unreg_button">
                <span class="btn btn-danger position-absolute w-100 after_button">Meld av</span>
                <span class="btn btn-secondary w-100">Du er påmeldt</span>
            </a>
        {% elif activity.max_participants <= activity.registered_users.count %}
            <a href="#" class="btn btn-outline-secondary disabled" aria-disabled="true">Arrangementet er fullt</a>
        {% else %}
            <a href="{% url 'events:register' activity.id %}" class="btn btn-primary mt-1 stretched-link">Meld deg på</a>
        {% endif %}
    {% else %}
        <a href="{% url 'usermanagement:login' %}" class="btn btn-outline-primary stretched-link" role="button">Logg inn for å melde deg på</a>
    {% endif %}
{% endif %}

activate/events/templates/events/activity_create.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Lag aktivitet!</legend>
            {{ form|crispy }}
        </fieldset>
        <input type="submit" class="btn btn-primary w-100" value="Lag aktivitet">
    </form>
{% endblock content %}

activate/events/templates/events/activity_detail_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="d-flex flex-row">
        <div style="" class="col-md-4 mr-2 ">
            <div class="activate-card bg-white shadow">
                {% if activity.krever_NTNUI_medlemskap %}
                    <img src="{% static "images/ntnui_logo_800.png" %}" style="width: 100%;"  alt="NTNUI-logo"/>
                {% else %}
                    <img src="{% static "images/sit_logo_800.png" %}" style="width: 100%;" alt="Bilde av aktivitet"/>
                {% endif %}


                <div class="p-4">

                    {% if activity.krever_NTNUI_medlemskap %}
                        <div class="mb-2">
                            <p>Dette arrangementet krever NTNUI-medlemskap</p>
                        </div>
                    {% endif %}

                    <div class="mb-2">
                        <strong>Arrangør</strong>
                        <br>
                        <div class="font-weight-light">
                            {% if activity.responsible.first_name|length == 0 and activity.responsible.last_name|length == 0 %}
                                Arrangør har ikke fullført registering.
                            {% else %}
                                {{ activity.responsible.first_name }} {{ activity.responsible.last_name }}
                            {% endif %}
                        </div>
                    </div>
                    {% if activity.show_email_address %}
                    <div class="mb-2">
                        <strong>Kontaktinformasjon</strong>
                        <br>
                        <div class="font-weight-light">
                                {{ activity.responsible.email }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="mb-2">
                        <strong>Påmeldte</strong>
                        <br>
                        <div class="font-weight-light">
                            {% if activity.max_participants == 0 or activity.max_participants is None %}
                                {{ activity.registered_users.count }}
                            {% else %}
                                {{ activity.registered_users.count }} av {{ activity.max_participants }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="mb-2">
                        <strong>Oppmøtested</strong>
                        <br>
                        <div class="font-weight-light">
                            {% if activity.meeting_place|length == 0 or activity.meeting_place is None %}
                                Ta kontakt med arrangør.
                            {% else %}
                                {{ activity.meeting_place }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="mb-2">
                        <strong>Utstyr</strong>
                        <br>
                        <div class="font-weight-light">
                            {% if activity.gear|length == 0 or activity.gear is None %}
                                Ingen utstyr påkrevd.
                            {% else %}
                                {{ activity.gear }}
                            {% endif %}
                        </div>
                    </div>
                    {% if activity.price > 0 %}
                        <div class="mb-2">
                            <strong>Pris</strong>
                            <br>
                            <div class="font-weight-light">
                                {{ activity.price }} kr
                            </div>
                        </div>
                    {% endif %}
                    <div class="">
                        <br>
                        {% include "events/activity_show_users.html" with users=activity.registered_users %}
                        <br>
                    </div>
                </div>
            </div>
        </div>

        <div class="w-100">
            <div class="activate-card bg-white shadow p-4">
                <div class="d-flex flex-column flex-grow w-100">
                    <a href="/{{ activity.id }}" class=""><h4>{{ activity.title }}</h4></a>
                    <small class="text-muted mb-2">{{ activity.date }}, fra {{ activity.time_from }} til {{ activity.time_to }}.</small>
                    <div class="d-flex flex-column flex-grow position-relative">
                        <div style="word-break: break-word;" class="">{{ activity.text|linebreaksbr }}</div>
                    </div>
                </div>
                <div class="d-flex flex-column position-relative mt-3">
                    {% include 'events/activity_button_reg_detail.html' %}
                </div>
            </div>
            {% if activity.responsible == request.user and not activity.cancelled and activity.date > date %}
                <div class="mt-4 text-center">
                    <a class="text-danger" href="{% url 'events:cancel_activity' activity.id %}">Avlyst arrangement</a>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock content %}

activate/events/templates/events/activity_item.html
{% load static %}

<div style="position: relative; width: 100%; height: 255px;" class="activate-card mb-4 bg-white d-flex flex-row shadow">
  {% if activity.krever_NTNUI_medlemskap %}
      <img src="{% static "images/ntnui_logo_800.png" %}" class="h-100 image-container" alt="NTNUI-logo"/>
  {% else %}
    <img src="{% static "images/sit_logo_800.png" %}" class="h-100 image-container" alt="Bilde av aktivitet"/>
  {% endif %}

    <div style="" class="d-flex flex-column flex-grow w-100">
        <div class="w-100 h-100 p-4">
            <div class="d-flex flex-column flex-grow w-100 h-100">

                <div class="d-flex flex-column flex-grow w-100 h-100">

                    <a href="/{{ activity.id }}" class="stretched-link"><h4>{{ activity.title }}</h4></a>
                    <small class="text-muted mb-2">{{ activity.date }}, fra {{ activity.time_from }} til {{ activity.time_to }}.</small>
                    <div class="d-flex flex-column flex-grow position-relative h-100">
                        <div style="display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;" class="position-absolute w-100 h-100">
                            <p style="overflow: hidden;" class="">{{ activity.text|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-column position-relative">
                  {% include 'events/activity_button_register.html' %}
                </div>
            </div>
        </div>
    </div>
</div>

activate/events/templates/events/activity_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container-fluid mb-4" id="accordion">
  {% if not user.is_authenticated %}
      <div class="activate-card shadow mb-4">
          <div class="card-header" align="center">
              <h3 class="mb-2">Activate!</h3>
          </div>
          <div class="card-body" align="left">
              <p>
                  Inaktivitet er et voksende problem i Norge. Unge i 2020 beveger seg alt for lite i løpet av en dag.
                  I tillegg til dette er ensomhet blant studenter et reelt problem.
              </p>
              <p>
                  Sit ønsker derfor å utvikle et produkt hvor folk kan legge ut forskjellige aktiviteter, og hvor de
                  kan åpne for at andre studenter også kan være med. Eksempler på slike aktiviteter kan være å spille
                  fotball, volleyball, dra å klatre, osv. Som bruker kan man melde seg på de arrangementer man ønsker å
                  delta på.
              </p>
              <div align="center">
                  <legend class="border-bottom mb-2"></legend>
                  <a class="btn btn-primary ml-1" align="center" href={% url 'usermanagement:signup' %}>
                      Bli med i dag!
                  </a>
              </div>
          </div>
      </div>
      {% endif %}
    <div class="activate-card shadow">
      <div class="card-header" id="headingFilter">
        <h5 class="mb-0">
          <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseFilter" aria-expanded="true" aria-controls="collapseFilter">
            <i class="fas fa-filter"></i> Filtreringsvalg
          </button>
        </h5>
      </div>

      <div id="collapseFilter" class="collapse" aria-labelledby="headingFilter" data-parent="#accordion">
        <div class="card-body">
           <form action="{% url 'events:activity_list' %}" method="GET">
            {% crispy filter_form %}
           </form>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
      <div class="list-group">
          {% for activity in activities %}
              {% include "events/activity_item.html" with activity=activity %}
          {% endfor %}
      </div>
  </div>
{% endblock content %}

activate/events/templates/events/activity_show_users.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Se påmeldte!
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Påmeldte brukere</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if users.all|length == 0 %}
          <p>Ingen påmeldte brukere</p>
        {% else %}
          <ul class="list-unstyled">
          {% for user in users.all %}
            {% if user.profile.anonymous %}
              <li class="">Anonym bruker</li>
            {% else %}
              <li class="">{{user.first_name}} {{user.last_name}}</li>
            {% endif %}
          {% endfor %}
          </ul>
      {% endif %}

      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

activate/events/templates/events/activity_upcoming.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <div class="list-group">
            <legend class="border-bottom mb-4">Dine arrangementer!</legend>
            {% for activity in arranged_activities %}
                {% include "events/activity_item.html" with activity=activity %}
            {% endfor %}
            {% if arranged_activities.count == 0 %}
                <p>Du er ikke arrangør for noen arrangementer.</p>
            {% endif %}
        </div>

        <div class="list-group mt-5">
            <legend class="border-bottom mb-4 mt-5">Kommende arrangementer!</legend>
            {% for activity in upcoming_activities %}
                {% include "events/activity_item.html" with activity=activity %}
            {% endfor %}
            {% if upcoming_activities.count == 0 %}
                <p>Du har ingen kommende arrangementer.</p>
            {% endif %}
        </div>


        <div class="list-group mt-5">
            <legend class="border-bottom mb-4 mt-5">Dine tidligere arrangementer!</legend>
            {% for activity in earlier_arranged_activities %}
                {% include "events/activity_item.html" with activity=activity %}
            {% endfor %}
            {% if earlier_arranged_activities.count == 0 %}
                <p>Du er har ikke vært arrangør for noen tidligere arrangementer.</p>
            {% endif %}
        </div>


        <div class="list-group mt-5">
            <legend class="border-bottom mb-4 mt-5">Tidligere påmeldte arrangementer!</legend>
            {% for activity in earlier_activities %}
                {% include "events/activity_item.html" with activity=activity %}
            {% endfor %}
            {% if earlier_activities.count == 0 %}
                <p>Du er har ikke vært på noen tidligere arrangementer.</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}